alter table public.listings
  add column if not exists original_price numeric(12,2),
  add column if not exists sale_price numeric(12,2),
  add column if not exists short_description text,
  add column if not exists card_badge text,
  add column if not exists thumbnail_b_url text,
  add column if not exists winning_thumbnail text check (winning_thumbnail in ('a', 'b')),
  add column if not exists auto_optimize_card boolean not null default false;

alter table public.listings
  add constraint listings_original_price_nonnegative check (original_price is null or original_price >= 0),
  add constraint listings_sale_price_nonnegative check (sale_price is null or sale_price >= 0),
  add constraint listings_sale_below_original check (
    sale_price is null or original_price is null or sale_price < original_price
  );

create table if not exists public.product_offers (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.listings(id) on delete cascade,
  seller_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  sale_price numeric(12,2) not null check (sale_price >= 0),
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  limit_type text not null default 'none' check (limit_type in ('none', 'first_customers', 'until_sold_out', 'weekend')),
  max_redemptions integer check (max_redemptions is null or max_redemptions > 0),
  redemption_count integer not null default 0 check (redemption_count >= 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_at > starts_at),
  check (limit_type <> 'first_customers' or max_redemptions is not null)
);

create table if not exists public.product_conversion_events (
  id bigint generated by default as identity primary key,
  listing_id uuid not null references public.listings(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  session_id text not null,
  event_type text not null check (event_type in ('impression', 'click', 'view', 'add_to_cart', 'checkout_started')),
  card_variant text check (card_variant in ('a', 'b')),
  surface text not null default 'unknown' check (surface in ('home', 'search', 'storefront', 'feed', 'product', 'checkout', 'unknown')),
  created_at timestamptz not null default now()
);

create index if not exists product_offers_listing_schedule_idx
  on public.product_offers (listing_id, starts_at, ends_at)
  where is_active = true;

create index if not exists product_offers_seller_updated_idx
  on public.product_offers (seller_id, updated_at desc);

create index if not exists product_conversion_listing_event_created_idx
  on public.product_conversion_events (listing_id, event_type, created_at desc);

create index if not exists product_conversion_session_created_idx
  on public.product_conversion_events (session_id, created_at desc);

alter table public.product_offers enable row level security;
alter table public.product_conversion_events enable row level security;

create policy "Anyone can read active product offers"
  on public.product_offers for select
  to anon, authenticated
  using (is_active = true or (select auth.uid()) = seller_id);

create policy "Sellers can create their product offers"
  on public.product_offers for insert
  to authenticated
  with check (
    (select auth.uid()) = seller_id
    and exists (
      select 1 from public.listings
      where listings.id = product_offers.listing_id
        and listings.seller_id = (select auth.uid())
    )
  );

create policy "Sellers can update their product offers"
  on public.product_offers for update
  to authenticated
  using ((select auth.uid()) = seller_id)
  with check ((select auth.uid()) = seller_id);

create policy "Sellers can delete their product offers"
  on public.product_offers for delete
  to authenticated
  using ((select auth.uid()) = seller_id);

create policy "Visitors can record public product funnel events"
  on public.product_conversion_events for insert
  to anon, authenticated
  with check (
    (user_id is null or user_id = (select auth.uid()))
    and exists (
      select 1 from public.listings
      where listings.id = product_conversion_events.listing_id
        and listings.status in ('active', 'published')
    )
  );

create policy "Sellers can read their product funnel events"
  on public.product_conversion_events for select
  to authenticated
  using (
    exists (
      select 1 from public.listings
      where listings.id = product_conversion_events.listing_id
        and listings.seller_id = (select auth.uid())
    )
  );

grant select on public.product_offers to anon, authenticated;
grant insert, update, delete on public.product_offers to authenticated;
grant insert on public.product_conversion_events to anon, authenticated;
grant select on public.product_conversion_events to authenticated;
grant usage, select on sequence public.product_conversion_events_id_seq to anon, authenticated;
