alter table public.sites
  add column if not exists indexing_enabled boolean not null default true,
  add column if not exists indexing_status text not null default 'not_submitted'
    check (indexing_status in ('not_submitted','submitted','failed','disabled')),
  add column if not exists last_indexing_requested_at timestamptz,
  add column if not exists ai_text_enhancement_enabled boolean not null default false;

alter table public.site_analytics_events
  drop constraint if exists site_analytics_events_event_type_check;

alter table public.site_analytics_events
  add constraint site_analytics_events_event_type_check
  check (event_type in (
    'page_view','route_change','session_start','session_end','engagement',
    'outbound_click','download_click','button_click','form_submit','conversion',
    'web_vital','scroll_depth','site_error'
  )),
  add column if not exists event_name text,
  add column if not exists metric_name text,
  add column if not exists metric_value double precision;

alter table public.site_analytics_daily
  add column if not exists conversions bigint not null default 0,
  add column if not exists form_submissions bigint not null default 0,
  add column if not exists errors bigint not null default 0;

create table if not exists public.site_analytics_metrics_daily (
  id bigint generated by default as identity primary key,
  site_id uuid not null references public.sites(id) on delete cascade,
  release_id uuid references public.site_releases(id) on delete set null,
  event_date date not null,
  metric_name text not null check (metric_name in ('LCP','CLS','INP','FCP','TTFB')),
  sample_count bigint not null default 0,
  metric_total double precision not null default 0,
  metric_min double precision,
  metric_max double precision,
  updated_at timestamptz not null default now(),
  unique nulls not distinct (site_id, release_id, event_date, metric_name)
);

create table if not exists public.site_indexing_submissions (
  id uuid primary key default gen_random_uuid(),
  site_id uuid not null references public.sites(id) on delete cascade,
  release_id uuid references public.site_releases(id) on delete set null,
  provider text not null check (provider in ('indexnow')),
  status text not null check (status in ('submitted','failed')),
  url_count integer not null default 0 check (url_count between 0 and 10000),
  response_status integer,
  submitted_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists site_indexing_submissions_site_submitted_idx
  on public.site_indexing_submissions(site_id, submitted_at desc);
create index if not exists site_analytics_metrics_site_date_idx
  on public.site_analytics_metrics_daily(site_id, event_date desc);
create index if not exists site_analytics_events_advanced_idx
  on public.site_analytics_events(site_id, event_type, occurred_at desc)
  where event_type in ('conversion','form_submit','web_vital','scroll_depth','site_error');

alter table public.site_analytics_metrics_daily enable row level security;
alter table public.site_indexing_submissions enable row level security;

create policy site_metrics_managers_read on public.site_analytics_metrics_daily
for select to authenticated
using (exists (
  select 1 from public.sites s
  where s.id = site_id and private.can_manage_business(s.business_id)
));

create policy site_indexing_managers_read on public.site_indexing_submissions
for select to authenticated
using (exists (
  select 1 from public.sites s
  where s.id = site_id and private.can_manage_business(s.business_id)
));

create policy site_metrics_service_all on public.site_analytics_metrics_daily
for all to service_role using (true) with check (true);
create policy site_indexing_service_all on public.site_indexing_submissions
for all to service_role using (true) with check (true);

grant select on public.site_analytics_metrics_daily, public.site_indexing_submissions to authenticated;
grant all on public.site_analytics_metrics_daily, public.site_indexing_submissions to service_role;
grant usage, select on sequence public.site_analytics_metrics_daily_id_seq to service_role;

create or replace function public.ingest_site_analytics_event(event_payload jsonb)
returns uuid
language plpgsql
security definer
set search_path = public, pg_catalog
as $$
declare
  created_event_id uuid;
  event_day date := ((event_payload->>'occurred_at')::timestamptz at time zone 'UTC')::date;
  event_site_id uuid := (event_payload->>'site_id')::uuid;
  event_release_id uuid := nullif(event_payload->>'release_id','')::uuid;
  event_kind text := event_payload->>'event_type';
  visitor_inserted integer := 0;
  dimension_pair record;
begin
  insert into public.site_analytics_events (
    site_id,release_id,event_type,session_id_hash,visitor_id_hash,path,referrer_domain,outbound_url_domain,element_label,
    utm_source,utm_medium,utm_campaign,utm_content,utm_term,landing_page,exit_page,country_code,device_type,
    browser_family,os_family,engaged_seconds,is_bounce,event_name,metric_name,metric_value,occurred_at
  ) values (
    event_site_id,event_release_id,event_kind,event_payload->>'session_id_hash',nullif(event_payload->>'visitor_id_hash',''),event_payload->>'path',
    nullif(event_payload->>'referrer_domain',''),nullif(event_payload->>'outbound_url_domain',''),nullif(event_payload->>'element_label',''),
    nullif(event_payload->>'utm_source',''),nullif(event_payload->>'utm_medium',''),nullif(event_payload->>'utm_campaign',''),nullif(event_payload->>'utm_content',''),nullif(event_payload->>'utm_term',''),
    nullif(event_payload->>'landing_page',''),nullif(event_payload->>'exit_page',''),nullif(event_payload->>'country_code',''),nullif(event_payload->>'device_type',''),
    nullif(event_payload->>'browser_family',''),nullif(event_payload->>'os_family',''),nullif(event_payload->>'engaged_seconds','')::integer,nullif(event_payload->>'is_bounce','')::boolean,
    nullif(event_payload->>'event_name',''),nullif(event_payload->>'metric_name',''),nullif(event_payload->>'metric_value','')::double precision,
    (event_payload->>'occurred_at')::timestamptz
  ) returning id into created_event_id;

  if nullif(event_payload->>'visitor_id_hash','') is not null then
    insert into public.site_analytics_visitor_days (site_id,event_date,visitor_id_hash)
    values (event_site_id,event_day,event_payload->>'visitor_id_hash') on conflict do nothing;
    get diagnostics visitor_inserted = row_count;
  end if;

  insert into public.site_analytics_daily (
    site_id,release_id,event_date,page_views,sessions,consented_visitors,engaged_seconds,clicks,bounces,
    conversions,form_submissions,errors
  ) values (
    event_site_id,event_release_id,event_day,
    case when event_kind in ('page_view','route_change') then 1 else 0 end,
    case when event_kind = 'session_start' then 1 else 0 end,
    visitor_inserted,
    coalesce(nullif(event_payload->>'engaged_seconds','')::integer,0),
    case when event_kind in ('outbound_click','download_click','button_click','conversion','form_submit') then 1 else 0 end,
    case when coalesce(nullif(event_payload->>'is_bounce','')::boolean,false) then 1 else 0 end,
    case when event_kind = 'conversion' then 1 else 0 end,
    case when event_kind = 'form_submit' then 1 else 0 end,
    case when event_kind = 'site_error' then 1 else 0 end
  ) on conflict (site_id,release_id,event_date) do update set
    page_views = site_analytics_daily.page_views + excluded.page_views,
    sessions = site_analytics_daily.sessions + excluded.sessions,
    consented_visitors = site_analytics_daily.consented_visitors + excluded.consented_visitors,
    engaged_seconds = site_analytics_daily.engaged_seconds + excluded.engaged_seconds,
    clicks = site_analytics_daily.clicks + excluded.clicks,
    bounces = site_analytics_daily.bounces + excluded.bounces,
    conversions = site_analytics_daily.conversions + excluded.conversions,
    form_submissions = site_analytics_daily.form_submissions + excluded.form_submissions,
    errors = site_analytics_daily.errors + excluded.errors,
    updated_at = now();

  if event_kind in ('page_view','route_change','engagement','session_end') then
    insert into public.site_analytics_top_pages_daily (site_id,release_id,event_date,path,page_views,entries,exits,engaged_seconds)
    values (
      event_site_id,event_release_id,event_day,event_payload->>'path',
      case when event_kind in ('page_view','route_change') then 1 else 0 end,
      case when event_kind = 'session_start' or event_payload->>'landing_page' = event_payload->>'path' then 1 else 0 end,
      case when event_kind = 'session_end' then 1 else 0 end,
      coalesce(nullif(event_payload->>'engaged_seconds','')::integer,0)
    ) on conflict (site_id,release_id,event_date,path) do update set
      page_views = site_analytics_top_pages_daily.page_views + excluded.page_views,
      entries = site_analytics_top_pages_daily.entries + excluded.entries,
      exits = site_analytics_top_pages_daily.exits + excluded.exits,
      engaged_seconds = site_analytics_top_pages_daily.engaged_seconds + excluded.engaged_seconds,
      updated_at = now();
  end if;

  if event_kind = 'web_vital'
    and event_payload->>'metric_name' in ('LCP','CLS','INP','FCP','TTFB')
    and nullif(event_payload->>'metric_value','') is not null
  then
    insert into public.site_analytics_metrics_daily (
      site_id,release_id,event_date,metric_name,sample_count,metric_total,metric_min,metric_max
    ) values (
      event_site_id,event_release_id,event_day,event_payload->>'metric_name',1,
      (event_payload->>'metric_value')::double precision,(event_payload->>'metric_value')::double precision,(event_payload->>'metric_value')::double precision
    ) on conflict (site_id,release_id,event_date,metric_name) do update set
      sample_count = site_analytics_metrics_daily.sample_count + 1,
      metric_total = site_analytics_metrics_daily.metric_total + excluded.metric_total,
      metric_min = least(site_analytics_metrics_daily.metric_min, excluded.metric_min),
      metric_max = greatest(site_analytics_metrics_daily.metric_max, excluded.metric_max),
      updated_at = now();
  end if;

  for dimension_pair in
    select * from (values
      ('referrer',nullif(event_payload->>'referrer_domain','')),
      ('country',nullif(event_payload->>'country_code','')),
      ('device',nullif(event_payload->>'device_type','')),
      ('browser',nullif(event_payload->>'browser_family','')),
      ('os',nullif(event_payload->>'os_family','')),
      ('utm_campaign',nullif(event_payload->>'utm_campaign','')),
      ('outbound',case when event_kind = 'outbound_click' then nullif(event_payload->>'outbound_url_domain','') end),
      ('download',case when event_kind = 'download_click' then nullif(event_payload->>'path','') end),
      ('goal',case when event_kind = 'conversion' then nullif(event_payload->>'event_name','') end),
      ('form',case when event_kind = 'form_submit' then nullif(event_payload->>'event_name','') end),
      ('scroll_depth',case when event_kind = 'scroll_depth' then nullif(event_payload->>'event_name','') end),
      ('error',case when event_kind = 'site_error' then nullif(event_payload->>'event_name','') end)
    ) as dims(dimension,value) where value is not null
  loop
    insert into public.site_analytics_dimensions_daily (site_id,release_id,event_date,dimension,value,event_count)
    values (event_site_id,event_release_id,event_day,dimension_pair.dimension,dimension_pair.value,1)
    on conflict (site_id,release_id,event_date,dimension,value) do update
    set event_count = site_analytics_dimensions_daily.event_count + 1, updated_at = now();
  end loop;
  return created_event_id;
end;
$$;

revoke all on function public.ingest_site_analytics_event(jsonb) from public;
grant execute on function public.ingest_site_analytics_event(jsonb) to service_role;

comment on column public.sites.indexing_status is
  'Tracks discovery submission state only. Search engines independently decide whether and when a URL is indexed.';
comment on table public.site_indexing_submissions is
  'Server-side search discovery submissions. Acceptance does not guarantee crawl, index, or ranking.';
comment on table public.site_analytics_metrics_daily is
  'Aggregated Web Vitals without raw page content, form values, IP addresses, or browser identifiers.';
